version: '3'
services:

  db:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD="admin@123"
    ports:
      '8080:8080'

  pythonapp:
    build: /usr/app/src/python/
    command: python3 /usr/app/src/Database.py

