services:
  db:
    image: "mysql:latest"
    environment:
      MYSQL_DATABASE: "studentDetails"
      MYSQL_ROOT_PASSWORD: "admin@123"
    ports:
      - '1234:1234'

  pythonapp:
    build: ./python/
    command: python3 ./Login.py
    depends_on:
    	- mysql
